# Generated by Django 4.2.16 on 2025-01-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_visit_options_visit_city_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
