# Generated by Django 4.2.16 on 2025-01-29 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_visit_user_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='city',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='city_text',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='country_text',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='ip_text',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='longitude',
        ),
    ]
