# Generated by Django 4.2.16 on 2025-01-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_remove_visit_city_remove_visit_city_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
